/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.compani.finaz.Views;

import com.compani.finaz.Entitys.Cliente;
import com.compani.finaz.Entitys.Solicitud;
import com.compani.finaz.Views.consulta.ConsultaIinterface;
import com.compani.finaz.Views.menuInterfaces.MenuAccion;
import com.compani.finaz.lib.imagen.FilterImageFormat;
import com.compani.finaz.Controllers.ClienteController;
import com.compani.finaz.tablesModel.ClienteTableModel;
import java.awt.Image;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Blob;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


public class PnCliente extends javax.swing.JPanel implements MenuAccion, ConsultaIinterface<Cliente> {

    Cliente cliente = new Cliente();
    ClienteTableModel tmCliente = new ClienteTableModel();
    private int longitudBytes;
    FileInputStream fisfoto;
    Solicitud soli = new Solicitud();
    List listCliente;
    List<Cliente> lCliente = new ArrayList<>();
    ClienteController mCliente = new ClienteController();

    /**
     * Creates new form PnCliente2
     * @throws java.sql.SQLException
     */
    public PnCliente() throws SQLException{
        
        initComponents();    

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnConsultaCliente1 = new com.compani.finaz.Views.PnConsultaCliente();
        pnContenedor = new javax.swing.JPanel();
        pnCliente = new javax.swing.JPanel();
        jXLabel3 = new org.jdesktop.swingx.JXLabel();
        tabbepnDatos = new javax.swing.JTabbedPane();
        pnPersonales = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        dateFechaNacimiento = new org.jdesktop.swingx.JXDatePicker();
        jLabel55 = new javax.swing.JLabel();
        jsLimite = new javax.swing.JSpinner();
        jLabel28 = new javax.swing.JLabel();
        cbSexo = new javax.swing.JComboBox();
        tfOcupacion = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tfApellido = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        cbEstadoCivil = new javax.swing.JComboBox();
        jLabel56 = new javax.swing.JLabel();
        dateFechaRegistro = new org.jdesktop.swingx.JXDatePicker();
        jPanel1 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        tfCelular = new javax.swing.JFormattedTextField();
        tfDireccion = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        tfCuidad = new javax.swing.JTextField();
        tfTelefono = new javax.swing.JFormattedTextField();
        jLabel60 = new javax.swing.JLabel();
        pnLaborales = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        tfEmpresa = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        tfIngreso = new javax.swing.JTextField();
        tfCargo = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        dateFechaIngreso = new org.jdesktop.swingx.JXDatePicker();
        jPanel2 = new javax.swing.JPanel();
        tfDepartamento = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        tfCuidadTrabajo = new javax.swing.JTextField();
        tfTelefonoTrabajo = new javax.swing.JFormattedTextField();
        jLabel62 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        tfExt = new javax.swing.JTextField();
        tfJefe = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        tfDireccionTrabajo = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tCliente = new javax.swing.JTable();
        cbTipoIndentificacion = new javax.swing.JComboBox();
        tfIdentificacion = new javax.swing.JFormattedTextField();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        lbCodigo = new org.jdesktop.swingx.JXLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jXHeader2 = new org.jdesktop.swingx.JXHeader();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        lbfoto = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1206, 694));

        pnContenedor.setLayout(new java.awt.CardLayout());

        pnCliente.setBackground(new java.awt.Color(255, 255, 255));
        pnCliente.setPreferredSize(new java.awt.Dimension(1206, 655));

        jXLabel3.setForeground(new java.awt.Color(0, 161, 152));
        jXLabel3.setText("Identificación");
        jXLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tabbepnDatos.setBackground(new java.awt.Color(255, 255, 255));
        tabbepnDatos.setForeground(new java.awt.Color(0, 161, 152));
        tabbepnDatos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        pnPersonales.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(0, 161, 152));
        jLabel1.setText("Nombre");

        jLabel24.setForeground(new java.awt.Color(0, 161, 152));
        jLabel24.setText("Fecha nacimiento");

        jLabel55.setForeground(new java.awt.Color(0, 161, 152));
        jLabel55.setText("Límite");

        jLabel28.setForeground(new java.awt.Color(0, 161, 152));
        jLabel28.setText("Sexo");

        cbSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M", "F" }));
        cbSexo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbSexoKeyPressed(evt);
            }
        });

        jLabel57.setForeground(new java.awt.Color(0, 161, 152));
        jLabel57.setText("Ocupación");

        jLabel19.setForeground(new java.awt.Color(0, 161, 152));
        jLabel19.setText("Apellido");

        jLabel51.setForeground(new java.awt.Color(0, 161, 152));
        jLabel51.setText("Estado civil");

        cbEstadoCivil.setForeground(new java.awt.Color(0, 161, 152));
        cbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Soltero", "Casado", "Viud@", "Union libre" }));

        jLabel56.setForeground(new java.awt.Color(0, 161, 152));
        jLabel56.setText("Fecha Reg");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contacto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 161, 152))); // NOI18N

        jLabel54.setForeground(new java.awt.Color(0, 161, 152));
        jLabel54.setText("E-mail");

        try {
            tfCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###)###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfCelular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfCelularFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCelularFocusLost(evt);
            }
        });
        tfCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfCelularKeyPressed(evt);
            }
        });

        jLabel59.setForeground(new java.awt.Color(0, 161, 152));
        jLabel59.setText("Cuidad");

        jLabel53.setForeground(new java.awt.Color(0, 161, 152));
        jLabel53.setText("Celular");

        jLabel52.setForeground(new java.awt.Color(0, 161, 152));
        jLabel52.setText("Teléfono");

        try {
            tfTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###)###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfTelefonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfTelefonoFocusLost(evt);
            }
        });
        tfTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfTelefonoKeyPressed(evt);
            }
        });

        jLabel60.setForeground(new java.awt.Color(0, 161, 152));
        jLabel60.setText("Dirección");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel60)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel53)
                        .addComponent(jLabel52)))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfDireccion)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel54))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel59)))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCuidad, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel53)
                    .addComponent(tfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel54)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel59)
                    .addComponent(tfCuidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52)
                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel60, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(tfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnPersonalesLayout = new javax.swing.GroupLayout(pnPersonales);
        pnPersonales.setLayout(pnPersonalesLayout);
        pnPersonalesLayout.setHorizontalGroup(
            pnPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPersonalesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPersonalesLayout.createSequentialGroup()
                        .addGroup(pnPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel55)
                            .addComponent(jLabel1)
                            .addComponent(jLabel24)
                            .addComponent(jLabel28))
                        .addGap(4, 4, 4)
                        .addGroup(pnPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNombre)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPersonalesLayout.createSequentialGroup()
                                .addGroup(pnPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnPersonalesLayout.createSequentialGroup()
                                        .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel57))
                                    .addGroup(pnPersonalesLayout.createSequentialGroup()
                                        .addComponent(dateFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                                        .addComponent(jLabel51))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnPersonalesLayout.createSequentialGroup()
                                        .addComponent(jsLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel56)))
                                .addGap(4, 4, 4)
                                .addGroup(pnPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateFechaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(tfApellido))
                        .addGap(25, 25, 25))
                    .addGroup(pnPersonalesLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        pnPersonalesLayout.setVerticalGroup(
            pnPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPersonalesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24)
                    .addGroup(pnPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dateFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel51)
                        .addComponent(cbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel57))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55)
                    .addComponent(jsLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateFechaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel56))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        tabbepnDatos.addTab("Personales", pnPersonales);

        pnLaborales.setBackground(new java.awt.Color(255, 255, 255));

        jLabel25.setForeground(new java.awt.Color(0, 161, 152));
        jLabel25.setText("Empresa");

        jLabel29.setForeground(new java.awt.Color(0, 161, 152));
        jLabel29.setText("Ingreso");

        jLabel30.setForeground(new java.awt.Color(0, 161, 152));
        jLabel30.setText("Cargo");

        jLabel58.setForeground(new java.awt.Color(0, 161, 152));
        jLabel58.setText("Fecha ingreso");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contacto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 161, 152))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(430, 118));

        jLabel63.setForeground(new java.awt.Color(0, 161, 152));
        jLabel63.setText("Dirección");

        try {
            tfTelefonoTrabajo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###)###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfTelefonoTrabajo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfTelefonoTrabajoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfTelefonoTrabajoFocusLost(evt);
            }
        });
        tfTelefonoTrabajo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfTelefonoTrabajoKeyPressed(evt);
            }
        });

        jLabel62.setForeground(new java.awt.Color(0, 161, 152));
        jLabel62.setText("Teléfono");

        jLabel32.setForeground(new java.awt.Color(0, 161, 152));
        jLabel32.setText("Jefe");

        tfExt.setText("ext");
        tfExt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfExtMouseClicked(evt);
            }
        });

        jLabel61.setForeground(new java.awt.Color(0, 161, 152));
        jLabel61.setText("Departamento");

        jLabel31.setForeground(new java.awt.Color(0, 161, 152));
        jLabel31.setText("Cuidad");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel62, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel61, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel63, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tfTelefonoTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(tfExt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel32)
                        .addGap(18, 18, 18)
                        .addComponent(tfJefe, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfDireccionTrabajo)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tfDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfCuidadTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(tfJefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel62)
                    .addComponent(tfTelefonoTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfExt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(tfCuidadTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel61)
                    .addComponent(tfDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel63)
                    .addComponent(tfDireccionTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout pnLaboralesLayout = new javax.swing.GroupLayout(pnLaborales);
        pnLaborales.setLayout(pnLaboralesLayout);
        pnLaboralesLayout.setHorizontalGroup(
            pnLaboralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLaboralesLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(pnLaboralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(4, 4, 4)
                .addGroup(pnLaboralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(pnLaboralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel58, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(4, 4, 4)
                .addGroup(pnLaboralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addGroup(pnLaboralesLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnLaboralesLayout.setVerticalGroup(
            pnLaboralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLaboralesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnLaboralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(tfEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(tfCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnLaboralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(tfIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel58)
                    .addComponent(dateFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addGap(87, 87, 87))
        );

        tabbepnDatos.addTab("Laborales", pnLaborales);

        tCliente.setForeground(new java.awt.Color(0, 161, 152));
        tCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tCliente.setSelectionBackground(new java.awt.Color(0, 161, 152));
        tCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tClienteMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tCliente);

        cbTipoIndentificacion.setForeground(new java.awt.Color(0, 161, 152));
        cbTipoIndentificacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cedula", "Pasaporte" }));
        cbTipoIndentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoIndentificacionActionPerformed(evt);
            }
        });

        try {
            tfIdentificacion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-#######-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfIdentificacionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfIdentificacionKeyTyped(evt);
            }
        });

        jXLabel1.setForeground(new java.awt.Color(0, 161, 152));
        jXLabel1.setText("Codigo");
        jXLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lbCodigo.setText("   --   ");
        lbCodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(0, 161, 152));
        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Activo");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jXHeader2.setDescription("Registro de cliente");
        jXHeader2.setDescriptionFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jXHeader2.setDescriptionForeground(new java.awt.Color(0, 161, 152));
        jXHeader2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Data-Edit-48.png"))); // NOI18N
        jXHeader2.setTitle("Cliente");
        jXHeader2.setTitleFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jXHeader2.setTitleForeground(new java.awt.Color(0, 161, 152));

        jScrollPane1.setViewportView(jEditorPane1);

        lbfoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Portrait-128.png"))); // NOI18N
        lbfoto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        lbfoto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lbfoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbfotoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnClienteLayout = new javax.swing.GroupLayout(pnCliente);
        pnCliente.setLayout(pnClienteLayout);
        pnClienteLayout.setHorizontalGroup(
            pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXHeader2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnClienteLayout.createSequentialGroup()
                .addGroup(pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnClienteLayout.createSequentialGroup()
                        .addGroup(pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnClienteLayout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(135, 135, 135)
                                .addComponent(jXLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(cbTipoIndentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnClienteLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tabbepnDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnClienteLayout.createSequentialGroup()
                                .addComponent(tfIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(jCheckBox1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                                .addComponent(lbfoto))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)))
                    .addGroup(pnClienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4)))
                .addContainerGap())
        );
        pnClienteLayout.setVerticalGroup(
            pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnClienteLayout.createSequentialGroup()
                .addComponent(jXHeader2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnClienteLayout.createSequentialGroup()
                        .addGroup(pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbTipoIndentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox1))
                        .addGap(7, 7, 7)
                        .addComponent(tabbepnDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnClienteLayout.createSequentialGroup()
                        .addComponent(lbfoto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pnContenedor.add(pnCliente, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbTipoIndentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoIndentificacionActionPerformed
        FormatterTF();
    }//GEN-LAST:event_cbTipoIndentificacionActionPerformed

    private void tfTelefonoTrabajoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTelefonoTrabajoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTelefonoTrabajoFocusGained

    private void tfTelefonoTrabajoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTelefonoTrabajoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTelefonoTrabajoFocusLost

    private void tfTelefonoTrabajoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTelefonoTrabajoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTelefonoTrabajoKeyPressed

    private void tfExtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfExtMouseClicked
        tfExt.setText("");
    }//GEN-LAST:event_tfExtMouseClicked

    private void tfTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTelefonoKeyPressed

    }//GEN-LAST:event_tfTelefonoKeyPressed

    private void tfTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTelefonoFocusLost

    }//GEN-LAST:event_tfTelefonoFocusLost

    private void tfTelefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTelefonoFocusGained

    }//GEN-LAST:event_tfTelefonoFocusGained

    private void cbSexoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbSexoKeyPressed

    }//GEN-LAST:event_cbSexoKeyPressed

    private void tfCelularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCelularKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCelularKeyPressed

    private void tfCelularFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCelularFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCelularFocusLost

    private void tfCelularFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCelularFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCelularFocusGained

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed

    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void tClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tClienteMouseClicked
        if (evt.getClickCount() == 2) {
            ClienteTableModel tmCliente = (ClienteTableModel) tCliente.getModel();
            cliente = tmCliente.getCliente(tCliente.getSelectedRow());
            onSelectedValue(cliente);

        }

    }//GEN-LAST:event_tClienteMouseClicked

    private void tfIdentificacionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfIdentificacionKeyPressed
//        String identificacion = tfIdentificacion.getText().replace("-", "").trim();
//        if (identificacion.length() > 4) {
//            Cliente clien = ClienteController.getInstance().getClienteIdentificacion(tfIdentificacion.getText());
//  
//
//        }
    }//GEN-LAST:event_tfIdentificacionKeyPressed

    private void lbfotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbfotoMouseClicked
        if (evt.getClickCount() == 2) {

            JFileChooser se = new JFileChooser();
            se.setFileSelectionMode(JFileChooser.FILES_ONLY);
            se.addChoosableFileFilter(new FilterImageFormat());
            se.setAcceptAllFileFilterUsed(false);
            int estado = se.showOpenDialog(null);
            if (estado == JFileChooser.APPROVE_OPTION) {
                try {

                    fisfoto = new FileInputStream(se.getSelectedFile());
                    this.longitudBytes = (int) se.getSelectedFile().length();
                    System.out.println(longitudBytes);

                    Image icono = ImageIO.read(se.getSelectedFile()).getScaledInstance(lbfoto.getWidth(), lbfoto.getHeight(), Image.SCALE_DEFAULT);
                    lbfoto.setIcon(new ImageIcon(icono));
                    lbfoto.updateUI();

                } catch (FileNotFoundException ex) {
                    System.out.println(ex);
                } catch (IOException ex) {

                }
            }
        }
    }//GEN-LAST:event_lbfotoMouseClicked

    private void tfIdentificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfIdentificacionKeyTyped
//        // TODO add your handling code here:
//        listAsignatura = manejo.getlEstudiante("matricula", tfMatricula.getText().toLowerCase());
//        String formato = tfIdentificacion.getText().replace("","-");
        
//        listCliente = (List) ClienteController.getInstance().getClienteIdentificacion("identificacion",tfIdentificacion.getText().trim().replace("", "-"));
        tmCliente.setlCliente(listCliente);
//        ClienteController.getInstance().findAll();


    }//GEN-LAST:event_tfIdentificacionKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbEstadoCivil;
    private javax.swing.JComboBox cbSexo;
    private javax.swing.JComboBox cbTipoIndentificacion;
    private org.jdesktop.swingx.JXDatePicker dateFechaIngreso;
    private org.jdesktop.swingx.JXDatePicker dateFechaNacimiento;
    private org.jdesktop.swingx.JXDatePicker dateFechaRegistro;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private org.jdesktop.swingx.JXHeader jXHeader2;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel3;
    private javax.swing.JSpinner jsLimite;
    private org.jdesktop.swingx.JXLabel lbCodigo;
    private javax.swing.JLabel lbfoto;
    private javax.swing.JPanel pnCliente;
    private com.compani.finaz.Views.PnConsultaCliente pnConsultaCliente1;
    private javax.swing.JPanel pnContenedor;
    private javax.swing.JPanel pnLaborales;
    private javax.swing.JPanel pnPersonales;
    private javax.swing.JTable tCliente;
    private javax.swing.JTabbedPane tabbepnDatos;
    private javax.swing.JTextField tfApellido;
    private javax.swing.JTextField tfCargo;
    private javax.swing.JFormattedTextField tfCelular;
    private javax.swing.JTextField tfCuidad;
    private javax.swing.JTextField tfCuidadTrabajo;
    private javax.swing.JTextField tfDepartamento;
    private javax.swing.JTextField tfDireccion;
    private javax.swing.JTextField tfDireccionTrabajo;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfEmpresa;
    private javax.swing.JTextField tfExt;
    private javax.swing.JFormattedTextField tfIdentificacion;
    private javax.swing.JTextField tfIngreso;
    private javax.swing.JTextField tfJefe;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfOcupacion;
    private javax.swing.JFormattedTextField tfTelefono;
    private javax.swing.JFormattedTextField tfTelefonoTrabajo;
    // End of variables declaration//GEN-END:variables

    public Cliente getCliente() {
        return cliente;
    }

    private void FormatterTF() {
        String cb = (String) cbTipoIndentificacion.getSelectedItem();
        if ("Cedula".equals(cb)) {
            try {
                tfIdentificacion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-#######-#")));
            } catch (ParseException ex) {
                Logger.getLogger(PnPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if ("Pasaporte".equals(cb)) {
            tfIdentificacion.setFormatterFactory(null);
            tfIdentificacion.setText("");
        }
    }

    @Override
    public void save() {
//
        if (!filter()) {
            return;
        }
        if (cliente == null) {
            cliente = new Cliente();
        }

        // System.out.println("filtro");
        cliente.setIdentificacion(tfIdentificacion.getText());
        //personales
        cliente.setNombre(tfNombre.getText());
        cliente.setApellido(tfApellido.getText());
        cliente.setFechaNacimiento(dateFechaNacimiento.getDate());
        cliente.setEstadoCivil(cbEstadoCivil.getSelectedItem().toString());
        cliente.setSexo(cbSexo.getSelectedItem().toString());
        cliente.setTelefono(tfTelefono.getText());
        cliente.setCelular(tfCelular.getText());
        cliente.setEmail(tfEmail.getText());
        cliente.setLimite(jsLimite.getValue().toString());
        cliente.setFechaReg(dateFechaRegistro.getDate());
        cliente.setOcupacion(tfOcupacion.getText());
        cliente.setCuidad(tfCuidad.getText());
        cliente.setDirrecion(tfDireccion.getText());
        //laborales
        cliente.setEmpresa(tfEmpresa.getText());
        cliente.setCargo(tfCargo.getText());
        cliente.setIngreso(tfIngreso.getText());
        cliente.setDepartamento(tfDepartamento.getText());
        cliente.setFechaIngreso(dateFechaIngreso.getDate());
        cliente.setJefe(tfJefe.getText());
        cliente.setCuidadTrabajo(tfCuidadTrabajo.getText());
        cliente.setTelefonoTrabajo(tfTelefonoTrabajo.getText());
        cliente.setDirrecionTrabajo(tfDireccionTrabajo.getText());
        cliente.setActivo(jCheckBox1.isSelected());
        cliente.setImagen((Blob) fisfoto);

        soli.setCliente(cliente);
        ClienteController c = new ClienteController();
        c.save(cliente);
        clear();
        System.out.println("aqui");

    }

    @Override
    public void update() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void newObject() {
        clear();
        cliente = null;

    }

    @Override
    public List<JButton> getButtons() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void consulta() {
       
        pnConsultaCliente1.setConsultaInterface(this);
        pnContenedor.removeAll();
        try {
            pnConsultaCliente1.setTableModel();
        } catch (SQLException ex) {
            Logger.getLogger(PnCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        pnContenedor.add(pnConsultaCliente1);
        pnContenedor.revalidate();
        pnContenedor.repaint();
    }

    @Override
    public void closeAccion() {
        pnContenedor.removeAll();
        pnContenedor.add(pnCliente);
        pnContenedor.revalidate();
        pnContenedor.repaint();

        //tfNombre.setText(cliente.getNombre());
    }

    @Override
    public void onSelectedValue(Cliente value) {
        
        setCliente(value);
        

        closeAccion();
    }

    private boolean filter() {
        if (cbTipoIndentificacion.getSelectedItem().toString().equals("Pasaporte") && tfIdentificacion.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Debes especificar correctamente la Pasaporte");
            tfIdentificacion.requestFocus();
            return false;
        }
        if (cbTipoIndentificacion.getSelectedItem().toString().equals("Cedula") && tfIdentificacion.getText().trim().length() != 13) {
            JOptionPane.showMessageDialog(this, "Debes especificar correctamente la Cedula");
            tfIdentificacion.requestFocus();
            return false;
        }
        //Datos PErsonales        
        if (tfNombre.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes especificar el Nombre");
            tfNombre.requestFocus();
            return false;
        }

        if (tfApellido.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes especificar el Apellido");
            tfApellido.requestFocus();
            return false;
        }

        if (dateFechaNacimiento.getDate().toString().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes especificar la Fcha de nacimiento");
            dateFechaNacimiento.requestFocus();
            return false;
        }

        if (cbEstadoCivil.getSelectedIndex() <= -1) {
            JOptionPane.showMessageDialog(this, "Debes especificar el estado civil");
            cbEstadoCivil.requestFocus();
            return false;
        }
        if (cbSexo.getSelectedIndex() <= -1) {
            JOptionPane.showMessageDialog(this, "Debes especificar el sexo");
            cbSexo.requestFocus();
            return false;
        }
        if (tfTelefono.getText().length() != 13) {
            JOptionPane.showMessageDialog(this, "Debes especificar el teléfono");
            tfTelefono.requestFocus();
            return false;
        }
        if (tfCelular.getText().length() != 13) {
            JOptionPane.showMessageDialog(this, "Debes especificar el celular");
            tfCelular.requestFocus();
            return false;
        }
        if (tfEmail.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes especificar el E-mail");
            tfEmail.requestFocus();
            return false;
        }
        if (jsLimite.getValue().toString().length() <= 0) {
            JOptionPane.showMessageDialog(this, "Debes especificar el límite");
            jsLimite.requestFocus();
            return false;
        }
//        if (dateFechaRegistro.getDate().toString().length() <= 0) {
//            JOptionPane.showMessageDialog(this, "Debes especificar la fecha de registro");
//            dateFechaRegistro.requestFocus();
//            return false;
//        }
        if (tfOcupacion.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes especificar la ocupación");
            tfOcupacion.requestFocus();
            return false;
        }
        if (tfCuidad.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes especificar la cuidad");
            tfCuidad.requestFocus();
            return false;
        }
        if (tfDireccion.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes especificar la dirección");
            tfTelefono.requestFocus();
            return false;
        }
        //Datos Laborales
        if (tfEmpresa.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes especificar la empresa");
            tfEmpresa.requestFocus();
            return false;
        }
        if (tfCargo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes especificar el cargo");
            tfCargo.requestFocus();
            return false;
        }
        if (tfIngreso.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes especificar el ingreso");
            tfIngreso.requestFocus();
            return false;
        }
        if (tfDepartamento.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes especificar el departamento en que trabaja");
            tfDepartamento.requestFocus();
            return false;
        }
        if (dateFechaIngreso.getDate().toString().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes especificar la fecha que ingreso al trabajo");
            dateFechaIngreso.requestFocus();
            return false;
        }
        if (tfJefe.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes especificar el jefe de trabajo");
            tfDepartamento.requestFocus();
            return false;
        }
        if (tfCuidad.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes especificar la cuidad donde trabaja");
            tfCuidad.requestFocus();
            return false;
        }
        if (tfTelefonoTrabajo.getText().length() != 13) {
            JOptionPane.showMessageDialog(this, "Debes especificar el telefono del trabajo");
            tfTelefonoTrabajo.requestFocus();
            return false;
        }

        return true;

    }

    public void clear() {
        lbCodigo.setText("     --   ");
        tfIdentificacion.setText("");
        //Personales
        tfNombre.setText("");
        tfApellido.setText("");
        dateFechaNacimiento.setDate(null);
        cbEstadoCivil.setSelectedIndex(0);
        cbSexo.setSelectedIndex(0);
        tfTelefono.setText("");
        tfCelular.setText("");
        tfEmail.setText("");
        jsLimite.setValue(0);
        dateFechaRegistro.setDate(null);
        tfOcupacion.setText("");
        tfCuidad.setText("");
        tfDireccion.setText("");
        //Laborales
        tfEmpresa.setText("");
        tfCargo.setText("");
        tfIngreso.setText("");
        tfDepartamento.setText("");
        dateFechaIngreso.setDate(null);
        tfJefe.setText("");
        tfCuidadTrabajo.setText("");
        tfTelefonoTrabajo.setText("");
        tfDireccionTrabajo.setText("");
        jEditorPane1.setText("");
    }
//
//    private void TableModel() {
//        
//    ClienteController mcliente = new ClienteController();
//    List list = mcliente.getlClientes();
//    ClienteTableModel tCliente = new ClienteTableModel();
//    tCliente.setlCliente(list);
//    jTable3.setModel(tCliente);
//    
//    }

//    public void init() {
//        
//        try {
//            pnConsultaCliente1.setTableModel();
//        } catch (SQLException ex) {
//            Logger.getLogger(PnCliente.class.getName()).log(Level.SEVERE, null, ex);
//        }
//
//    }

    void init() throws SQLException {
        
        List<Cliente> lClientes = mCliente.getlClientes();
        tmCliente.setlCliente(lClientes);
        tCliente.setModel(tmCliente);
    }

    private void setCliente(Cliente value) {
       lbCodigo.setText(value.getId().toString());

        tfIdentificacion.setText(value.getIdentificacion());
        //Personal    
        tfNombre.setText(value.getNombre());
        tfApellido.setText(value.getApellido());

        dateFechaNacimiento.setDate(value.getFechaNacimiento());
        cbEstadoCivil.setSelectedItem(value.getEstadoCivil());
        cbSexo.setSelectedItem(value.getSexo());
        tfOcupacion.setText(value.getOcupacion());
        jsLimite.setValue(new Integer(value.getLimite()));
        dateFechaRegistro.setDate(value.getFechaIngreso());
        //Contacto
        tfCelular.setText(value.getCelular());
        tfEmail.setText(value.getEmail());
        tfTelefono.setText(value.getTelefono());
        tfCuidad.setText(value.getCuidad());
        tfDireccion.setText(value.getDirrecion());
        //Laborales
        tfEmpresa.setText(value.getEmpresa());
        tfCargo.setText(value.getCargo());
        tfIngreso.setText(value.getIngreso());
        dateFechaIngreso.setDate(value.getFechaIngreso());
        //Contacto
        tfTelefonoTrabajo.setText(value.getTelefonoTrabajo());
        tfJefe.setText(value.getJefe());
        tfDepartamento.setText(value.getDepartamento());
        tfCuidadTrabajo.setText(value.getCuidadTrabajo());
        tfDireccionTrabajo.setText(value.getDirrecionTrabajo());
        jCheckBox1.setSelected(value.isActivo());

        soli.setCliente(value);
    }

}
