/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.compani.finaz.Views;

import com.compani.finaz.Controllers.CuotasController;
import com.compani.finaz.Entitys.Cuota;
import com.compani.finaz.Entitys.SolicitudAutorizacion;
import com.compani.finaz.Views.consulta.ConsultaIinterface;
import com.compani.finaz.Views.menuInterfaces.MenuAccion;
import com.compani.finaz.tablesModel.CuotaTableModel;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.table.TableColumn;


public class PnCuotas extends javax.swing.JPanel implements MenuAccion, ConsultaIinterface<Object> {

    /**
     * Creates new form PnCuotas
     */
    CuotasController cCuota = new CuotasController();
    public PnCuotas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnConsultaSolicitudAutorizacion1 = new com.compani.finaz.Views.PnConsultaSolicitudAutorizacion();
        pnContenedor = new javax.swing.JPanel();
        pnCuota = new javax.swing.JPanel();
        jXHeader1 = new org.jdesktop.swingx.JXHeader();
        pnCliente = new javax.swing.JPanel();
        lbCliente1 = new javax.swing.JLabel();
        tfnombreCliente = new javax.swing.JTextField();
        btBuscarSolicitud = new javax.swing.JButton();
        lbCliente2 = new javax.swing.JLabel();
        lbcodigoCliente = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        lbNumeroDocumento = new javax.swing.JLabel();
        tfNumeroDocumento = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tfTotalImporte = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfNoCuotas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 255, 255));

        pnContenedor.setBackground(new java.awt.Color(255, 255, 255));
        pnContenedor.setLayout(new java.awt.CardLayout());

        jXHeader1.setDescription("Cobro de cuotas");
        jXHeader1.setDescriptionFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jXHeader1.setDescriptionForeground(new java.awt.Color(0, 161, 152));
        jXHeader1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Format-Numbering-01-48.png"))); // NOI18N
        jXHeader1.setTitle("Cuota");
        jXHeader1.setTitleFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jXHeader1.setTitleForeground(new java.awt.Color(0, 161, 152));

        pnCliente.setBackground(new java.awt.Color(255, 255, 255));
        pnCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Solicitud", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 161, 152))); // NOI18N

        lbCliente1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbCliente1.setForeground(new java.awt.Color(0, 161, 152));
        lbCliente1.setText("Cliente");

        tfnombreCliente.setSelectionColor(new java.awt.Color(0, 161, 152));
        tfnombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnombreClienteActionPerformed(evt);
            }
        });

        btBuscarSolicitud.setBackground(new java.awt.Color(0, 161, 152));
        btBuscarSolicitud.setForeground(new java.awt.Color(0, 161, 152));
        btBuscarSolicitud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Search-Find-24-3.png"))); // NOI18N
        btBuscarSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarSolicitudActionPerformed(evt);
            }
        });

        lbCliente2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbCliente2.setForeground(new java.awt.Color(0, 161, 152));
        lbCliente2.setText("Codigo");

        lbcodigoCliente.setText("      --         ");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable3);

        lbNumeroDocumento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbNumeroDocumento.setForeground(new java.awt.Color(0, 161, 152));
        lbNumeroDocumento.setText("Noº Solicitud");

        tfNumeroDocumento.setSelectionColor(new java.awt.Color(0, 161, 152));

        javax.swing.GroupLayout pnClienteLayout = new javax.swing.GroupLayout(pnCliente);
        pnCliente.setLayout(pnClienteLayout);
        pnClienteLayout.setHorizontalGroup(
            pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnClienteLayout.createSequentialGroup()
                .addGroup(pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnClienteLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnClienteLayout.createSequentialGroup()
                                .addComponent(lbCliente2)
                                .addGap(10, 10, 10)
                                .addComponent(lbcodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnClienteLayout.createSequentialGroup()
                                .addComponent(lbCliente1)
                                .addGap(10, 10, 10)
                                .addComponent(tfnombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnClienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbNumeroDocumento)
                        .addGap(10, 10, 10)
                        .addComponent(tfNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btBuscarSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnClienteLayout.setVerticalGroup(
            pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNumeroDocumento)
                    .addComponent(btBuscarSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCliente2)
                    .addComponent(lbcodigoCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfnombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCliente1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnClienteLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Coutas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 161, 152))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable1PropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setForeground(new java.awt.Color(0, 161, 152));
        jLabel4.setText("Cuotas a cobrar:");

        jLabel3.setForeground(new java.awt.Color(0, 161, 152));
        jLabel3.setText("Importe total.:");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtrar"));

        jCheckBox1.setText("Pendientes");

        jCheckBox2.setText("Pagas");

        jCheckBox3.setText("Mora");

        jCheckBox4.setText("Todas");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jCheckBox1)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox2)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox3)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNoCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(264, 264, 264)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfTotalImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfTotalImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(tfNoCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnCuotaLayout = new javax.swing.GroupLayout(pnCuota);
        pnCuota.setLayout(pnCuotaLayout);
        pnCuotaLayout.setHorizontalGroup(
            pnCuotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jXHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnCuotaLayout.setVerticalGroup(
            pnCuotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCuotaLayout.createSequentialGroup()
                .addComponent(jXHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pnContenedor.add(pnCuota, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnContenedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfnombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnombreClienteActionPerformed

    private void btBuscarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarSolicitudActionPerformed
        try {
            consultaSolicitud();
        } catch (SQLException ex) {
            Logger.getLogger(PnCuotas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btBuscarSolicitudActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        calcularImporte();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable1PropertyChange

    }//GEN-LAST:event_jTable1PropertyChange

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarSolicitud;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private org.jdesktop.swingx.JXHeader jXHeader1;
    private javax.swing.JLabel lbCliente1;
    private javax.swing.JLabel lbCliente2;
    private javax.swing.JLabel lbNumeroDocumento;
    private javax.swing.JLabel lbcodigoCliente;
    private javax.swing.JPanel pnCliente;
    private com.compani.finaz.Views.PnConsultaSolicitudAutorizacion pnConsultaSolicitudAutorizacion1;
    private javax.swing.JPanel pnContenedor;
    private javax.swing.JPanel pnCuota;
    private javax.swing.JTextField tfNoCuotas;
    private javax.swing.JTextField tfNumeroDocumento;
    private javax.swing.JTextField tfTotalImporte;
    private javax.swing.JTextField tfnombreCliente;
    // End of variables declaration//GEN-END:variables

    private void consultaSolicitud() throws SQLException {
        pnConsultaSolicitudAutorizacion1.setConsultaInterface(this);
        pnContenedor.removeAll();
        pnConsultaSolicitudAutorizacion1.setTableModel();
        pnContenedor.add(pnConsultaSolicitudAutorizacion1);
        pnContenedor.revalidate();
        pnContenedor.repaint();

    }

    @Override
    public void closeAccion() {
        pnContenedor.removeAll();
        pnContenedor.add(pnCuota);
        pnContenedor.revalidate();
        pnContenedor.repaint();

    }

    @Override
    public void onSelectedValue(Object value) {
        setSolicitud((SolicitudAutorizacion) value);
    }

    @Override
    public void save() {
        CuotaTableModel tcuotas = (CuotaTableModel) jTable1.getModel();
        List list = tcuotas.getlCuota();
        
        for (Iterator it = list.iterator(); it.hasNext();) {
            Cuota cuotas = (Cuota) it.next(); 
            cCuota.save(cuotas);
        }
        
       
    } 

    @Override
    public void update() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void newObject() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public List<JButton> getButtons() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setSolicitud(SolicitudAutorizacion solicitud) {

        tfNumeroDocumento.setText(solicitud.getSolicitud().getNoSolicitud());
        tfnombreCliente.setText(solicitud.getSolicitud().getCliente().getNombre() + " " + solicitud.getSolicitud().getCliente().getApellido());
        lbcodigoCliente.setText(String.valueOf(solicitud.getSolicitud().getCliente().getId()));
        CuotasController cCuotas = new CuotasController();
        CuotaTableModel tmCuotas = new CuotaTableModel();
        List list = cCuotas.getlCuotas(solicitud.getId());
        tmCuotas.setlCuota(list);
        jTable1.setModel(tmCuotas);
        TableColumn tableColumn = jTable1.getColumnModel().getColumn(1);
        JComboBox cbtipoAsistencia;
        List list5 = new ArrayList<>();
        list5.add("PAGO");

        cbtipoAsistencia = new JComboBox(list5.toArray());
        tableColumn.setCellEditor(new DefaultCellEditor(cbtipoAsistencia));
    }

    public JTextField getTfTotalImporte() {
        return tfTotalImporte;
    }

    public void setTfTotalImporte(String importe) {
        tfTotalImporte.setText(importe);
    }

    private void calcularImporte() {
        CuotaTableModel tmCuota = (CuotaTableModel) jTable1.getModel();
        tfTotalImporte.setText(String.valueOf(tmCuota.getMonto()));
        tfNoCuotas.setText(String.valueOf(tmCuota.getNoCuota()));
    }

}
