/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.compani.finaz.Views;

import com.compani.finaz.Entitys.Cliente;
import com.compani.finaz.Views.menuInterfaces.MenuAccion;
import com.compani.finaz.utility.JdbcConfiguration;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;



public class PnPrincipal extends javax.swing.JFrame {

    MenuAccion tabSeleccionada;
    Cliente cliente = new Cliente();

    /**
     * Creates new form PnPrincipal
     * @throws java.sql.SQLException
     */
    public PnPrincipal() throws SQLException{
        initComponents();
        JdbcConfiguration.init();
        init();
//        tabSeleccionada = (MenuAccion) pnCliente;
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedSelector21 = new org.edisoncor.gui.tabbedPane.TabbedSelector2();
        jPanel1 = new javax.swing.JPanel();
        pnCuotas1 = new com.compani.finaz.Views.PnCuotas();
        pnSolicitud1 = new com.compani.finaz.Views.PnSolicitud();
        try {
            pnCliente1 = new com.compani.finaz.Views.PnCliente();
        } catch (java.sql.SQLException e1) {
            e1.printStackTrace();
        }
        pnAutorizacion1 = new com.compani.finaz.Views.PnAutorizacion();
        pnToolbar = new org.edisoncor.gui.panel.Panel();
        btCancelar = new javax.swing.JButton();
        btGuardar = new javax.swing.JButton();
        btImprimir = new javax.swing.JButton();
        btConsulta = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        mbPrincipal = new com.alee.laf.menu.WebMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tabbedSelector21.setColorBackGround(new java.awt.Color(0, 161, 152));
        tabbedSelector21.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabbedSelector21StateChanged(evt);
            }
        });
        tabbedSelector21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabbedSelector21MouseClicked(evt);
            }
        });

        jPanel1.setLayout(new java.awt.CardLayout());
        jPanel1.add(pnCuotas1, "card2");

        tabbedSelector21.addTab("Cuotas", jPanel1);
        tabbedSelector21.addTab("Solicitud", pnSolicitud1);
        tabbedSelector21.addTab("Cliente", pnCliente1);
        tabbedSelector21.addTab("Autorizar", pnAutorizacion1);

        pnToolbar.setBackground(new java.awt.Color(255, 255, 255));
        pnToolbar.setForeground(new java.awt.Color(0, 204, 204));
        pnToolbar.setColorPrimario(new java.awt.Color(0, 161, 152));
        pnToolbar.setColorSecundario(new java.awt.Color(0, 161, 152));

        btCancelar.setBackground(new java.awt.Color(0, 161, 152));
        btCancelar.setForeground(new java.awt.Color(0, 161, 152));
        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cancel-48.png"))); // NOI18N
        btCancelar.setToolTipText("Cancelar");
        btCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btGuardar.setBackground(new java.awt.Color(0, 161, 152));
        btGuardar.setForeground(new java.awt.Color(0, 161, 152));
        btGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Floppy-48-2.png"))); // NOI18N
        btGuardar.setToolTipText("Guardar");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });

        btImprimir.setBackground(new java.awt.Color(0, 161, 152));
        btImprimir.setForeground(new java.awt.Color(0, 161, 152));
        btImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Printer-48.png"))); // NOI18N
        btImprimir.setToolTipText("Imprimir");
        btImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImprimirActionPerformed(evt);
            }
        });

        btConsulta.setBackground(new java.awt.Color(0, 161, 152));
        btConsulta.setForeground(new java.awt.Color(0, 161, 152));
        btConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Find-Replace-48-2-menu.png"))); // NOI18N
        btConsulta.setToolTipText("Consulta");
        btConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultaActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout pnToolbarLayout = new javax.swing.GroupLayout(pnToolbar);
        pnToolbar.setLayout(pnToolbarLayout);
        pnToolbarLayout.setHorizontalGroup(
            pnToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnToolbarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnToolbarLayout.setVerticalGroup(
            pnToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnToolbarLayout.createSequentialGroup()
                .addGroup(pnToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnToolbarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(pnToolbarLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(pnToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(8, 8, 8))
        );

        mbPrincipal.setBackground(java.awt.Color.RED);
        mbPrincipal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 161, 152), new java.awt.Color(0, 161, 152), new java.awt.Color(0, 161, 152), new java.awt.Color(0, 161, 152)));
        mbPrincipal.setForeground(new java.awt.Color(0, 161, 152));
        mbPrincipal.setToolTipText("");

        jMenu3.setBackground(new java.awt.Color(203, 138, 73));
        jMenu3.setForeground(new java.awt.Color(0, 161, 152));
        jMenu3.setText("Administracion");

        jMenuItem1.setText("Opciones");
        jMenu3.add(jMenuItem1);

        mbPrincipal.add(jMenu3);

        jMenu4.setForeground(new java.awt.Color(0, 161, 152));
        jMenu4.setText("Procesos");
        mbPrincipal.add(jMenu4);

        jMenu1.setForeground(new java.awt.Color(0, 161, 152));
        jMenu1.setText("Reportes");

        jMenuItem2.setText("Rellenar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        mbPrincipal.add(jMenu1);

        setJMenuBar(mbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnToolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabbedSelector21, javax.swing.GroupLayout.PREFERRED_SIZE, 1257, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tabbedSelector21, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImprimirActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btImprimirActionPerformed

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        save();
    }//GEN-LAST:event_btGuardarActionPerformed

    private void tabbedSelector21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabbedSelector21MouseClicked
        InstanciaMenu(); 
    }//GEN-LAST:event_tabbedSelector21MouseClicked

    private void tabbedSelector21StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabbedSelector21StateChanged

    }//GEN-LAST:event_tabbedSelector21StateChanged

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        tabSeleccionada.newObject();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultaActionPerformed
        consulta();
    }//GEN-LAST:event_btConsultaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              
                try {
                    new PnPrincipal().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(PnPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btConsulta;
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btImprimir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private com.alee.laf.menu.WebMenuBar mbPrincipal;
    private com.compani.finaz.Views.PnAutorizacion pnAutorizacion1;
    private com.compani.finaz.Views.PnCliente pnCliente1;
    private com.compani.finaz.Views.PnCuotas pnCuotas1;
    private com.compani.finaz.Views.PnSolicitud pnSolicitud1;
    private org.edisoncor.gui.panel.Panel pnToolbar;
    private org.edisoncor.gui.tabbedPane.TabbedSelector2 tabbedSelector21;
    // End of variables declaration//GEN-END:variables

    private void save() {
        if (tabSeleccionada != null) {
            tabSeleccionada.save();
        }
//        pnSolicitud1.setCliente(pnCliente1.getCliente());

    }

    private void InstanciaMenu() {
        int index = tabbedSelector21.getSelectedIndex();
        tabSeleccionada = null;
        if (tabbedSelector21.getComponentAt(index) instanceof MenuAccion) {
            tabSeleccionada = (MenuAccion) tabbedSelector21.getComponentAt(index);
            
        }

//        if (tabbedSelector21.getComponentAt(index) instanceof MenuAccion1) {
//            tabSeleccionada = (MenuAccion) tabbedSelector21.getComponentAt(index);
//        }
    }

    private void consulta() {
        if (tabSeleccionada != null) {
            tabSeleccionada.consulta();
        }
    }

    private void init() throws SQLException{
        

//        pnCliente.init();
        pnSolicitud1.init();
        pnAutorizacion1.setTableModel();
        
        this.setExtendedState(MAXIMIZED_BOTH);
        
    }

}
