/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.compani.finaz.Views;

import com.compani.finaz.Controllers.SolicitudController;
import com.compani.finaz.Entitys.Cliente;
import com.compani.finaz.Entitys.Solicitud;
import com.compani.finaz.Entitys.garante.Garante;
import com.compani.finaz.Entitys.garante.Hipoteca;
import com.compani.finaz.Entitys.garante.Persona;
import com.compani.finaz.Entitys.garante.Vehiculo;
import com.compani.finaz.Views.consulta.ConsultaIinterface;
import com.compani.finaz.Views.menuInterfaces.MenuAccion;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;


public class PnSolicitud extends javax.swing.JPanel implements MenuAccion, ConsultaIinterface<Object> {

    /**
     * Creates new form PnSolicitud
     */
    Solicitud solicitud = new Solicitud();
    Cliente cliente = new Cliente();
    SolicitudController cSolicitud;

    List<Persona> lPersona;
    List<Hipoteca> lHipoteca;
    List<Vehiculo> lVehiculo;
    List<Garante> lGarante;

    public PnSolicitud() {
        this.cSolicitud = new SolicitudController();
        initComponents();
        init();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnConsultaCliente1 = new com.compani.finaz.Views.PnConsultaCliente();
        pnConsultaCliente2 = new com.compani.finaz.Views.PnConsultaCliente();
        pnConsultaSolicitud1 = new com.compani.finaz.Views.PnConsultaSolicitud();
        pnCliente = new javax.swing.JPanel();
        lbCliente = new javax.swing.JLabel();
        lbcodigo = new javax.swing.JLabel();
        lbCliente1 = new javax.swing.JLabel();
        tfnombre = new javax.swing.JTextField();
        btBuscarSolicitud = new javax.swing.JButton();
        jLabel55 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        pnContenedor = new javax.swing.JPanel();
        pnSolicitud = new javax.swing.JPanel();
        jXHeader1 = new org.jdesktop.swingx.JXHeader();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lbNumeroDocumento = new javax.swing.JLabel();
        tfNumeroDocumento = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tfMontoSolicitado = new javax.swing.JTextField();
        cbMetodoAmortizacion = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tfTasa = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        cbModalidadPago = new javax.swing.JComboBox();
        tfTiempo = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        tfTipo = new javax.swing.JComboBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        cbTiempo = new javax.swing.JComboBox();
        comGarante1 = new com.compani.finaz.Views.component.ComGarante();
        jLabel19 = new javax.swing.JLabel();
        tfCoutas = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lbCliente2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbCliente3 = new javax.swing.JLabel();
        tfNumeroDocumento1 = new javax.swing.JTextField();
        btBuscarSolicitud1 = new javax.swing.JButton();
        jLabel56 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();

        pnCliente.setBackground(new java.awt.Color(255, 255, 255));
        pnCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 161, 152))); // NOI18N

        lbCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbCliente.setForeground(new java.awt.Color(0, 161, 152));
        lbCliente.setText("Codigo");

        lbcodigo.setText("      --         ");

        lbCliente1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbCliente1.setForeground(new java.awt.Color(0, 161, 152));
        lbCliente1.setText("Nombre");

        tfnombre.setSelectionColor(new java.awt.Color(0, 161, 152));
        tfnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnombreActionPerformed(evt);
            }
        });

        btBuscarSolicitud.setBackground(new java.awt.Color(0, 161, 152));
        btBuscarSolicitud.setForeground(new java.awt.Color(0, 161, 152));
        btBuscarSolicitud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Search-Find-24-3.png"))); // NOI18N
        btBuscarSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarSolicitudActionPerformed(evt);
            }
        });

        jLabel55.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(0, 161, 152));
        jLabel55.setText("Deuda Actual");

        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout pnClienteLayout = new javax.swing.GroupLayout(pnCliente);
        pnCliente.setLayout(pnClienteLayout);
        pnClienteLayout.setHorizontalGroup(
            pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnClienteLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbCliente1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnClienteLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(lbcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(182, 182, 182)
                        .addComponent(btBuscarSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnClienteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel55)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );
        pnClienteLayout.setVerticalGroup(
            pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnClienteLayout.createSequentialGroup()
                .addGroup(pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnClienteLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel55))
                    .addGroup(pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnClienteLayout.createSequentialGroup()
                            .addGroup(pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbCliente)
                                    .addComponent(lbcodigo))
                                .addComponent(btBuscarSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(11, 11, 11)
                            .addGroup(pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbCliente1)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1206, 590));

        pnContenedor.setBackground(new java.awt.Color(255, 255, 255));
        pnContenedor.setLayout(new java.awt.CardLayout());

        jXHeader1.setDescription("Registro de solicitud");
        jXHeader1.setDescriptionFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jXHeader1.setDescriptionForeground(new java.awt.Color(0, 161, 152));
        jXHeader1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Documents-02-48.png"))); // NOI18N
        jXHeader1.setTitle("Solicitud");
        jXHeader1.setTitleFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jXHeader1.setTitleForeground(new java.awt.Color(0, 161, 152));

        jTabbedPane1.setForeground(new java.awt.Color(0, 161, 152));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1206, 655));

        lbNumeroDocumento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbNumeroDocumento.setForeground(new java.awt.Color(0, 161, 152));
        lbNumeroDocumento.setText("Noº Solicitud");

        tfNumeroDocumento.setSelectionColor(new java.awt.Color(0, 161, 152));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 161, 152));
        jLabel14.setText("Monto solicitado");

        tfMontoSolicitado.setSelectionColor(new java.awt.Color(0, 161, 152));
        tfMontoSolicitado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMontoSolicitadojTextField5ActionPerformed(evt);
            }
        });

        cbMetodoAmortizacion.setForeground(new java.awt.Color(0, 161, 152));
        cbMetodoAmortizacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Francés o de Cuotas constantes", "Americano o Al vencimiento", "Constante de capital o Italiano", "Cuotas crecientes", "Cuotas decrecientes", "Cuota fija con plazo variable" }));
        cbMetodoAmortizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMetodoAmortizacionjComboBox1ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 161, 152));
        jLabel15.setText("Metodo de amortizacion");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 161, 152));
        jLabel16.setText("Tasa de interes");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 161, 152));
        jLabel17.setText("Modalidad de Pago");

        cbModalidadPago.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Diario", "Quincenal", "Mensual", "Trimestral", "Cuatrimestral", "Anual", "" }));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 161, 152));
        jLabel18.setText("Tipo");

        tfTipo.setForeground(new java.awt.Color(0, 161, 152));
        tfTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Consumo", "Hipotecario", "Comercial", "Estudio" }));
        tfTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTipojComboBox3ActionPerformed(evt);
            }
        });

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(0, 161, 152));
        jCheckBox1.setText("Prioridad");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 161, 152));
        jLabel20.setText("Tiempo");

        cbTiempo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dia", "Meses", "Anos" }));
        cbTiempo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTiempoItemStateChanged(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 161, 152));
        jLabel19.setText("Cuotas");

        tfCoutas.setSelectionColor(new java.awt.Color(0, 161, 152));
        tfCoutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCoutasjTextField5ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 161, 152))); // NOI18N

        lbCliente2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbCliente2.setForeground(new java.awt.Color(0, 161, 152));
        lbCliente2.setText("Codigo");

        jLabel1.setText("      --         ");

        lbCliente3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbCliente3.setForeground(new java.awt.Color(0, 161, 152));
        lbCliente3.setText("Nombre");

        tfNumeroDocumento1.setSelectionColor(new java.awt.Color(0, 161, 152));
        tfNumeroDocumento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNumeroDocumento1ActionPerformed(evt);
            }
        });

        btBuscarSolicitud1.setBackground(new java.awt.Color(0, 161, 152));
        btBuscarSolicitud1.setForeground(new java.awt.Color(0, 161, 152));
        btBuscarSolicitud1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Search-Find-24-3.png"))); // NOI18N
        btBuscarSolicitud1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarSolicitud1ActionPerformed(evt);
            }
        });

        jLabel56.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(0, 161, 152));
        jLabel56.setText("Deuda Actul");

        jTextField7.setSelectionColor(new java.awt.Color(0, 161, 152));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7jTextField5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCliente2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbCliente3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfNumeroDocumento1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btBuscarSolicitud1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(106, 106, 106)
                .addComponent(jLabel56)
                .addGap(4, 4, 4)
                .addComponent(jTextField7)
                .addGap(156, 156, 156))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCliente2)
                            .addComponent(jLabel1)))
                    .addComponent(btBuscarSolicitud1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel56)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNumeroDocumento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCliente3))
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbNumeroDocumento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jCheckBox1)
                .addGap(516, 516, 516))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfMontoSolicitado)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfTasa, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCoutas))
                            .addComponent(tfTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(367, 367, 367)
                                .addComponent(jLabel15)
                                .addGap(4, 4, 4)
                                .addComponent(cbMetodoAmortizacion, 0, 1, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(457, 457, 457)
                                .addComponent(jLabel20)
                                .addGap(4, 4, 4)
                                .addComponent(tfTiempo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17)
                                .addGap(4, 4, 4)
                                .addComponent(cbModalidadPago, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(169, 169, 169))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(comGarante1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNumeroDocumento)
                    .addComponent(tfNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(tfMontoSolicitado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(tfTasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(tfCoutas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(tfTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMetodoAmortizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel20))
                            .addComponent(cbTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel17))
                            .addComponent(cbModalidadPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comGarante1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registro", jPanel1);

        javax.swing.GroupLayout pnSolicitudLayout = new javax.swing.GroupLayout(pnSolicitud);
        pnSolicitud.setLayout(pnSolicitudLayout);
        pnSolicitudLayout.setHorizontalGroup(
            pnSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, 1206, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1206, Short.MAX_VALUE)
        );
        pnSolicitudLayout.setVerticalGroup(
            pnSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSolicitudLayout.createSequentialGroup()
                .addComponent(jXHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnContenedor.add(pnSolicitud, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void tfTipojComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTipojComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTipojComboBox3ActionPerformed

    private void cbMetodoAmortizacionjComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMetodoAmortizacionjComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMetodoAmortizacionjComboBox1ActionPerformed

    private void tfMontoSolicitadojTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMontoSolicitadojTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMontoSolicitadojTextField5ActionPerformed

    private void tfnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnombreActionPerformed

    private void btBuscarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarSolicitudActionPerformed
        try {
            consultaCliente();
        } catch (SQLException ex) {
            Logger.getLogger(PnSolicitud.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btBuscarSolicitudActionPerformed

    private void cbTiempoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTiempoItemStateChanged
//        addModalidad();
    }//GEN-LAST:event_cbTiempoItemStateChanged

    private void tfCoutasjTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCoutasjTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCoutasjTextField5ActionPerformed

    private void tfNumeroDocumento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNumeroDocumento1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNumeroDocumento1ActionPerformed

    private void jTextField7jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7jTextField5ActionPerformed

    private void btBuscarSolicitud1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarSolicitud1ActionPerformed
        try {
            consultaCliente();
        } catch (SQLException ex) {
            Logger.getLogger(PnSolicitud.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btBuscarSolicitud1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarSolicitud;
    private javax.swing.JButton btBuscarSolicitud1;
    private javax.swing.JComboBox cbMetodoAmortizacion;
    private javax.swing.JComboBox cbModalidadPago;
    private javax.swing.JComboBox cbTiempo;
    private com.compani.finaz.Views.component.ComGarante comGarante1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextPane jTextPane1;
    private org.jdesktop.swingx.JXHeader jXHeader1;
    private javax.swing.JLabel lbCliente;
    private javax.swing.JLabel lbCliente1;
    private javax.swing.JLabel lbCliente2;
    private javax.swing.JLabel lbCliente3;
    private javax.swing.JLabel lbNumeroDocumento;
    private javax.swing.JLabel lbcodigo;
    private javax.swing.JPanel pnCliente;
    private com.compani.finaz.Views.PnConsultaCliente pnConsultaCliente1;
    private com.compani.finaz.Views.PnConsultaCliente pnConsultaCliente2;
    private com.compani.finaz.Views.PnConsultaSolicitud pnConsultaSolicitud1;
    private javax.swing.JPanel pnContenedor;
    private javax.swing.JPanel pnSolicitud;
    private javax.swing.JTextField tfCoutas;
    private javax.swing.JTextField tfMontoSolicitado;
    private javax.swing.JTextField tfNumeroDocumento;
    private javax.swing.JTextField tfNumeroDocumento1;
    private javax.swing.JSpinner tfTasa;
    private javax.swing.JSpinner tfTiempo;
    private javax.swing.JComboBox tfTipo;
    private javax.swing.JTextField tfnombre;
    // End of variables declaration//GEN-END:variables

    public void setCliente(Cliente cli) {
        if (cli != null) {
            cliente = cli;
            jLabel1.setText(cli.getId().toString());
            tfNumeroDocumento1.setText(cli.getNombre() + " " + cli.getApellido());
        }
    }
//    public void initaa(){
//        if(soli != null){
//    
//            lbcodigo.setText(soli.getCliente().getId().toString());
//            tfnombre.setText(soli.getCliente().getNombre()+" "+soli.getCliente().getApellido());
//        }
//    
//    }

    @Override
    public void save() {
        if (!filter()) {
            return;
        }
        if (solicitud == null) {
            solicitud = new Solicitud();
        }
        solicitud.setNoSolicitud(tfNumeroDocumento.getText());

        solicitud.setCliente(cliente);
        solicitud.setMonto(Integer.parseInt(tfMontoSolicitado.getText()));
        solicitud.setTasaInteres(Float.parseFloat(tfTasa.getValue().toString()));
        solicitud.setTipoPrestamo(tfTipo.getSelectedItem().toString());
        solicitud.setModalidadPago(cbModalidadPago.getSelectedItem().toString());
        solicitud.setTiempo(Integer.parseInt(tfTiempo.getValue().toString()));
        solicitud.setlPersona(comGarante1.getlPersona());
        solicitud.setlHipoteca(comGarante1.getlHipoteca());
        solicitud.setlVehiculo(comGarante1.getlVehiculo());
        solicitud.setCuotas(Integer.parseInt(tfCoutas.getText()));
        solicitud.setMetodoAmortizacion(cbMetodoAmortizacion.getSelectedItem().toString());
        solicitud.setTiempo2(cbTiempo.getSelectedItem().toString());
//           SolicitudController.getIntance().CreateOrUpdate(solicitud);
        SolicitudController cSolicitud = new SolicitudController();
        cSolicitud.save(solicitud);
        clear();
        

//           SolicitudController.CreateOrUpdate(solicitud);
    }

    @Override
    public void update() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void newObject() {
        clear();
    }

    @Override
    public List<JButton> getButtons() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void closeAccion() {
        pnContenedor.removeAll();
        pnContenedor.add(pnSolicitud);
        pnContenedor.revalidate();
        pnContenedor.repaint();
    }

    @Override
    public void consulta() {

        pnContenedor.removeAll();
        pnConsultaSolicitud1.setConsultaInterface(this);
        try {
            pnConsultaSolicitud1.setTableModel();
        } catch (SQLException ex) {
            Logger.getLogger(PnSolicitud.class.getName()).log(Level.SEVERE, null, ex);
        }
        pnContenedor.add(pnConsultaSolicitud1);
        pnContenedor.revalidate();
        pnContenedor.repaint();
    }

    void init() {
        comGarante1.init();
    }

    private void consultaCliente() throws SQLException {

        pnConsultaCliente1.setConsultaInterface(this);
        pnConsultaCliente1.setSolicitud(true);
        pnContenedor.removeAll();
        pnConsultaCliente1.setTableModel();
        pnContenedor.add(pnConsultaCliente1);
        pnContenedor.revalidate();
        pnContenedor.repaint();

    }

    @Override
    public void onSelectedValue(Object value) {
        if (value instanceof Solicitud) {
            setSolicitud((Solicitud) value);
        }

        if (value instanceof Cliente) {
            setCliente((Cliente) value);

        }

    }

    private void setSolicitud(Solicitud sol) {
        if (sol != null) {
            tfNumeroDocumento.setText(sol.getNoSolicitud());
            tfNumeroDocumento1.setText(sol.getCliente().getNombre() + " " + sol.getCliente().getApellido());
            jLabel1.setText(String.valueOf(sol.getCliente().getId()));
            tfMontoSolicitado.setText(String.valueOf(sol.getMonto()));
            tfTasa.setValue(sol.getTasaInteres());
            tfCoutas.setText(String.valueOf(sol.getCuotas()));
            tfTipo.setSelectedItem(sol.getTipoPrestamo());
            cbMetodoAmortizacion.setSelectedItem(sol.getMetodoAmortizacion());
            tfTiempo.setValue(sol.getTiempo());
            cbModalidadPago.setSelectedItem(sol.getModalidadPago());

        }
    }

    private boolean filter() {
        if (tfNumeroDocumento1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes especificar el cliente");
            tfNumeroDocumento1.requestFocus();
            return false;
        }
        if (tfMontoSolicitado.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes especificar el monto");
            tfMontoSolicitado.requestFocus();
            return false;
        }
        if (tfTasa.getValue().toString().equals("0")) {
            JOptionPane.showMessageDialog(this, "Debes especificar la tasa de interes");
            tfTasa.requestFocus();
            return false;
        }
        if (cbModalidadPago.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Debes especificar la modalidad de pago");
            cbModalidadPago.requestFocus();
            return false;
        }
        if (cbMetodoAmortizacion.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Debes especificar el metodo de amortizacion");
            cbMetodoAmortizacion.requestFocus();
            return false;
        }
        if (tfTipo.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Debes especificar el tipo");
            tfTipo.requestFocus();
            return false;
        }
        if (tfTiempo.getValue().toString().equals("0")) {
            JOptionPane.showMessageDialog(this, "Debes especificar la tasa de interes");
            tfTiempo.requestFocus();
            return false;
        }
        if ("".equals(tfCoutas.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Debes especificar las coutas");
            tfCoutas.requestFocus();
            return false;
        }

        return true;
    }
//    public Integer cantidadCuotas(){
//    
//    
//    
//    }

    private void addModalidad() {
        String combo = cbTiempo.getSelectedItem().toString();
        Integer tiempo = Integer.parseInt(tfTiempo.getValue().toString());
        switch (combo) {
            case "Dia":
                if (tiempo < 15) {
                    cbTiempo.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Dia"}));
                }
                if (tiempo > 15 && tiempo < 30) {
                    cbTiempo.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Dia", "Quincenal"}));
                }
                if (tiempo > 30 && tiempo < 90) {
                    cbTiempo.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Dia", "Quincenal", "Mes"}));
                }
                if (tiempo > 90 && tiempo < 120) {
                    cbTiempo.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Dia", "Quincenal", "Mes"}));
                }

        }
    }

    private void clear() {
        tfMontoSolicitado.setText("");
//        tfTasa.setValue("");
 
        tfCoutas.setText("");
        tfTipo.setSelectedIndex(-1);
        cbMetodoAmortizacion.setSelectedIndex(-1);
      
        cbTiempo.setSelectedIndex(-1);
        cbModalidadPago.setSelectedIndex(-1);
        tfnombre.setText("");
        lbcodigo.setText("      --         ");
        tfNumeroDocumento.setText("");
        comGarante1.clear();
        comGarante1.cleaHipoteca();
        comGarante1.clearPersona();
        comGarante1.clearVehiculo();

    }

}
