/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.compani.finaz.Views.component;

import com.compani.finaz.Entitys.garante.Hipoteca;
import com.compani.finaz.Entitys.garante.Persona;
import com.compani.finaz.Entitys.garante.Vehiculo;
import com.compani.finaz.tablesModel.PersonaGaranteTableModel;
import com.compani.finaz.tablesModel.HipotecaGaranteTableModelo;
import com.compani.finaz.tablesModel.VehiculoGaranteTableModel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;


public class ComGarante extends javax.swing.JPanel {

    /**
     * Creates new form PnGarante
     */
    VehiculoGaranteTableModel tmVehiculo = new VehiculoGaranteTableModel();
    PersonaGaranteTableModel tmCliene = new PersonaGaranteTableModel();
    HipotecaGaranteTableModelo tmHipoteca = new HipotecaGaranteTableModelo();
    List<Persona> lPersona = new ArrayList<>();
    List<Vehiculo> lVehiculo = new ArrayList<>();
    List<Hipoteca> lHipoteca = new ArrayList<>();

    public ComGarante() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnVehiculo = new org.edisoncor.gui.panel.PanelRound();
        lbChasis = new javax.swing.JLabel();
        tfChasisV = new org.edisoncor.gui.textField.TextFieldRoundImage();
        lbTipoV = new javax.swing.JLabel();
        tfTipoV = new org.edisoncor.gui.textField.TextFieldRoundImage();
        lbDescripcionV = new javax.swing.JLabel();
        lbPlacaV = new javax.swing.JLabel();
        tfPlacaV = new org.edisoncor.gui.textField.TextFieldRoundImage();
        lbMarcaV = new javax.swing.JLabel();
        tfMarcaV = new org.edisoncor.gui.textField.TextFieldRoundImage();
        lbModelo = new javax.swing.JLabel();
        lbValoracionV = new javax.swing.JLabel();
        tfValoracionV = new org.edisoncor.gui.textField.TextFieldRoundImage();
        tfDescripcion = new org.edisoncor.gui.textField.TextFieldRoundImage();
        tfModelo = new org.edisoncor.gui.textField.TextFieldRoundImage();
        pnHipoteca = new org.edisoncor.gui.panel.PanelRound();
        lbTituloH = new javax.swing.JLabel();
        tfNumeroExp = new org.edisoncor.gui.textField.TextFieldRoundImage();
        lbNombre1 = new javax.swing.JLabel();
        tfCodigo = new org.edisoncor.gui.textField.TextFieldRoundImage();
        lbTipoH = new javax.swing.JLabel();
        tfTipoH = new org.edisoncor.gui.textField.TextFieldRoundImage();
        lbValoracionH = new javax.swing.JLabel();
        tfIngreso1 = new org.edisoncor.gui.textField.TextFieldRoundImage();
        jLabel23 = new javax.swing.JLabel();
        tfdescripcion = new org.edisoncor.gui.textField.TextFieldRoundImage();
        pnTableVehiculo = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tVehiculo = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        pnTableHipoteca = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tHipoteca = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        pnTablePersona = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tCliente = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cbTipoGarante = new javax.swing.JComboBox();
        btClienteBuscar2 = new javax.swing.JButton();
        pnTipo = new javax.swing.JPanel();
        pnPersona = new org.edisoncor.gui.panel.PanelRound();
        lbCedula = new javax.swing.JLabel();
        tfCedula = new org.edisoncor.gui.textField.TextFieldRoundImage();
        lbNombre = new javax.swing.JLabel();
        tfNombre = new org.edisoncor.gui.textField.TextFieldRoundImage();
        lbApellido = new javax.swing.JLabel();
        tfApellido = new org.edisoncor.gui.textField.TextFieldRoundImage();
        lbCelular = new javax.swing.JLabel();
        tfCelular = new org.edisoncor.gui.textField.TextFieldRoundImage();
        lbTrabajo = new javax.swing.JLabel();
        tfTrabajo = new org.edisoncor.gui.textField.TextFieldRoundImage();
        lbPuesto = new javax.swing.JLabel();
        tfPuesto = new org.edisoncor.gui.textField.TextFieldRoundImage();
        lbIngreso = new javax.swing.JLabel();
        tfIngreso = new org.edisoncor.gui.textField.TextFieldRoundImage();
        lbJefe = new javax.swing.JLabel();
        tfJefe = new org.edisoncor.gui.textField.TextFieldRoundImage();
        lbTelefono = new javax.swing.JLabel();
        tfTelefono = new org.edisoncor.gui.textField.TextFieldRoundImage();
        pnTableGarante = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        pnVehiculo.setColorDeBorde(new java.awt.Color(0, 161, 152));
        pnVehiculo.setColorPrimario(new java.awt.Color(255, 255, 255));
        pnVehiculo.setColorSecundario(new java.awt.Color(255, 255, 255));
        pnVehiculo.setPreferredSize(new java.awt.Dimension(402, 194));

        lbChasis.setForeground(new java.awt.Color(0, 161, 152));
        lbChasis.setText("Chasis");

        lbTipoV.setForeground(new java.awt.Color(0, 161, 152));
        lbTipoV.setText("Tipo");

        lbDescripcionV.setForeground(new java.awt.Color(0, 161, 152));
        lbDescripcionV.setText("Descripcion");

        lbPlacaV.setForeground(new java.awt.Color(0, 161, 152));
        lbPlacaV.setText("Placa");

        lbMarcaV.setForeground(new java.awt.Color(0, 161, 152));
        lbMarcaV.setText("Marca");

        lbModelo.setForeground(new java.awt.Color(0, 161, 152));
        lbModelo.setText("Modelo");

        lbValoracionV.setForeground(new java.awt.Color(0, 161, 152));
        lbValoracionV.setText("Valoracion");

        javax.swing.GroupLayout pnVehiculoLayout = new javax.swing.GroupLayout(pnVehiculo);
        pnVehiculo.setLayout(pnVehiculoLayout);
        pnVehiculoLayout.setHorizontalGroup(
            pnVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnVehiculoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTipoV, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbChasis, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbModelo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbDescripcionV, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnVehiculoLayout.createSequentialGroup()
                        .addGroup(pnVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfTipoV, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(tfModelo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfChasisV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPlacaV, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbMarcaV, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbValoracionV, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfPlacaV, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(tfMarcaV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfValoracionV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnVehiculoLayout.setVerticalGroup(
            pnVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnVehiculoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbChasis)
                    .addComponent(tfChasisV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPlacaV)
                    .addComponent(tfPlacaV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMarcaV)
                    .addComponent(tfMarcaV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbModelo)
                    .addComponent(tfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTipoV)
                    .addComponent(tfTipoV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbValoracionV)
                    .addComponent(tfValoracionV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDescripcionV))
                .addGap(20, 20, 20))
        );

        pnHipoteca.setBackground(new java.awt.Color(255, 255, 255));
        pnHipoteca.setColorDeBorde(new java.awt.Color(0, 161, 152));
        pnHipoteca.setColorPrimario(new java.awt.Color(255, 255, 255));
        pnHipoteca.setColorSecundario(new java.awt.Color(255, 255, 255));
        pnHipoteca.setPreferredSize(new java.awt.Dimension(402, 194));

        lbTituloH.setForeground(new java.awt.Color(0, 161, 152));
        lbTituloH.setText("Numero EXP");

        tfNumeroExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNumeroExpActionPerformed(evt);
            }
        });

        lbNombre1.setForeground(new java.awt.Color(0, 161, 152));
        lbNombre1.setText("Codigo");

        lbTipoH.setForeground(new java.awt.Color(0, 161, 152));
        lbTipoH.setText("Tipo");

        lbValoracionH.setForeground(new java.awt.Color(0, 161, 152));
        lbValoracionH.setText("Valoracion");

        jLabel23.setForeground(new java.awt.Color(0, 161, 152));
        jLabel23.setText("Descripcion");

        javax.swing.GroupLayout pnHipotecaLayout = new javax.swing.GroupLayout(pnHipoteca);
        pnHipoteca.setLayout(pnHipotecaLayout);
        pnHipotecaLayout.setHorizontalGroup(
            pnHipotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHipotecaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnHipotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTituloH, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbNombre1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(4, 4, 4)
                .addGroup(pnHipotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnHipotecaLayout.createSequentialGroup()
                        .addGroup(pnHipotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNumeroExp, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(tfCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(pnHipotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbValoracionH, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbTipoH, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(4, 4, 4)
                        .addGroup(pnHipotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfTipoH, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(tfIngreso1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(tfdescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnHipotecaLayout.setVerticalGroup(
            pnHipotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHipotecaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnHipotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTituloH)
                    .addComponent(tfNumeroExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTipoH)
                    .addComponent(tfTipoH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnHipotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombre1)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbValoracionH)
                    .addComponent(tfIngreso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnHipotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(25, 25, 25))
        );

        tVehiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tVehiculo);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 161, 152));
        jLabel3.setText("Vehiculo");

        javax.swing.GroupLayout pnTableVehiculoLayout = new javax.swing.GroupLayout(pnTableVehiculo);
        pnTableVehiculo.setLayout(pnTableVehiculoLayout);
        pnTableVehiculoLayout.setHorizontalGroup(
            pnTableVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTableVehiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnTableVehiculoLayout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnTableVehiculoLayout.setVerticalGroup(
            pnTableVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTableVehiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addContainerGap())
        );

        tHipoteca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tHipoteca);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 161, 152));
        jLabel4.setText("Hipoteca");

        javax.swing.GroupLayout pnTableHipotecaLayout = new javax.swing.GroupLayout(pnTableHipoteca);
        pnTableHipoteca.setLayout(pnTableHipotecaLayout);
        pnTableHipotecaLayout.setHorizontalGroup(
            pnTableHipotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTableHipotecaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnTableHipotecaLayout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnTableHipotecaLayout.setVerticalGroup(
            pnTableHipotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTableHipotecaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addContainerGap())
        );

        tCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tCliente);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 161, 152));
        jLabel1.setText("Persona");

        javax.swing.GroupLayout pnTablePersonaLayout = new javax.swing.GroupLayout(pnTablePersona);
        pnTablePersona.setLayout(pnTablePersonaLayout);
        pnTablePersonaLayout.setHorizontalGroup(
            pnTablePersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTablePersonaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnTablePersonaLayout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnTablePersonaLayout.setVerticalGroup(
            pnTablePersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTablePersonaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Garantes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 161, 152))); // NOI18N
        setPreferredSize(new java.awt.Dimension(1150, 260));

        cbTipoGarante.setForeground(new java.awt.Color(0, 161, 152));
        cbTipoGarante.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Persona", "Vehiculo", "Hipoteca" }));
        cbTipoGarante.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTipoGaranteItemStateChanged(evt);
            }
        });
        cbTipoGarante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoGaranteActionPerformed(evt);
            }
        });

        btClienteBuscar2.setBackground(new java.awt.Color(0, 161, 152));
        btClienteBuscar2.setForeground(new java.awt.Color(0, 161, 152));
        btClienteBuscar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Add-New-24-3.png"))); // NOI18N
        btClienteBuscar2.setToolTipText("Añadir garante");
        btClienteBuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClienteBuscar2ActionPerformed(evt);
            }
        });

        pnTipo.setBackground(new java.awt.Color(255, 255, 255));
        pnTipo.setMinimumSize(new java.awt.Dimension(402, 194));
        pnTipo.setLayout(new java.awt.CardLayout());

        pnPersona.setBackground(new java.awt.Color(255, 255, 255));
        pnPersona.setColorDeBorde(new java.awt.Color(0, 161, 152));
        pnPersona.setColorPrimario(new java.awt.Color(255, 255, 255));
        pnPersona.setColorSecundario(new java.awt.Color(255, 255, 255));
        pnPersona.setPreferredSize(new java.awt.Dimension(402, 194));

        lbCedula.setForeground(new java.awt.Color(0, 161, 152));
        lbCedula.setText("Cedula");

        lbNombre.setForeground(new java.awt.Color(0, 161, 152));
        lbNombre.setText("Nombre");

        lbApellido.setForeground(new java.awt.Color(0, 161, 152));
        lbApellido.setText("Apellido");

        lbCelular.setForeground(new java.awt.Color(0, 161, 152));
        lbCelular.setText("Celular");

        lbTrabajo.setForeground(new java.awt.Color(0, 161, 152));
        lbTrabajo.setText("Telefono");

        tfTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTrabajoActionPerformed(evt);
            }
        });

        lbPuesto.setForeground(new java.awt.Color(0, 161, 152));
        lbPuesto.setText("Puesto");

        lbIngreso.setForeground(new java.awt.Color(0, 161, 152));
        lbIngreso.setText("Ingreso");

        lbJefe.setForeground(new java.awt.Color(0, 161, 152));
        lbJefe.setText("Jefe");

        lbTelefono.setForeground(new java.awt.Color(0, 161, 152));
        lbTelefono.setText("Trabajo");

        javax.swing.GroupLayout pnPersonaLayout = new javax.swing.GroupLayout(pnPersona);
        pnPersona.setLayout(pnPersonaLayout);
        pnPersonaLayout.setHorizontalGroup(
            pnPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPersonaLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pnPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCedula, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbApellido, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbCelular, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbTrabajo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(tfCelular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfTrabajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfCedula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPuesto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbIngreso, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbJefe, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbTelefono, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfJefe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(tfIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfPuesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32))
        );
        pnPersonaLayout.setVerticalGroup(
            pnPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPersonaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCedula)
                    .addComponent(tfCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPuesto)
                    .addComponent(tfPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombre)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbIngreso)
                    .addComponent(tfIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbApellido)
                    .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbJefe)
                    .addComponent(tfJefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbTelefono)
                        .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbCelular)
                        .addComponent(tfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTrabajo)
                    .addComponent(tfTrabajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );

        pnTipo.add(pnPersona, "card2");

        pnTableGarante.setLayout(new java.awt.CardLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 161, 152));
        jLabel2.setText("Tipo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cbTipoGarante, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128)
                        .addComponent(btClienteBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112)
                .addComponent(pnTableGarante, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnTableGarante, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbTipoGarante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addComponent(btClienteBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbTipoGaranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoGaranteActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbTipoGaranteActionPerformed

    private void tfTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTrabajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTrabajoActionPerformed

    private void btClienteBuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClienteBuscar2ActionPerformed
        addGarante();
    }//GEN-LAST:event_btClienteBuscar2ActionPerformed

    private void tfNumeroExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNumeroExpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNumeroExpActionPerformed

    private void cbTipoGaranteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTipoGaranteItemStateChanged
        changePanel();

    }//GEN-LAST:event_cbTipoGaranteItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClienteBuscar2;
    private javax.swing.JComboBox cbTipoGarante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbApellido;
    private javax.swing.JLabel lbCedula;
    private javax.swing.JLabel lbCelular;
    private javax.swing.JLabel lbChasis;
    private javax.swing.JLabel lbDescripcionV;
    private javax.swing.JLabel lbIngreso;
    private javax.swing.JLabel lbJefe;
    private javax.swing.JLabel lbMarcaV;
    private javax.swing.JLabel lbModelo;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbNombre1;
    private javax.swing.JLabel lbPlacaV;
    private javax.swing.JLabel lbPuesto;
    private javax.swing.JLabel lbTelefono;
    private javax.swing.JLabel lbTipoH;
    private javax.swing.JLabel lbTipoV;
    private javax.swing.JLabel lbTituloH;
    private javax.swing.JLabel lbTrabajo;
    private javax.swing.JLabel lbValoracionH;
    private javax.swing.JLabel lbValoracionV;
    private org.edisoncor.gui.panel.PanelRound pnHipoteca;
    private org.edisoncor.gui.panel.PanelRound pnPersona;
    private javax.swing.JPanel pnTableGarante;
    private javax.swing.JPanel pnTableHipoteca;
    private javax.swing.JPanel pnTablePersona;
    private javax.swing.JPanel pnTableVehiculo;
    private javax.swing.JPanel pnTipo;
    private org.edisoncor.gui.panel.PanelRound pnVehiculo;
    private javax.swing.JTable tCliente;
    private javax.swing.JTable tHipoteca;
    private javax.swing.JTable tVehiculo;
    private org.edisoncor.gui.textField.TextFieldRoundImage tfApellido;
    private org.edisoncor.gui.textField.TextFieldRoundImage tfCedula;
    private org.edisoncor.gui.textField.TextFieldRoundImage tfCelular;
    private org.edisoncor.gui.textField.TextFieldRoundImage tfChasisV;
    private org.edisoncor.gui.textField.TextFieldRoundImage tfCodigo;
    private org.edisoncor.gui.textField.TextFieldRoundImage tfDescripcion;
    private org.edisoncor.gui.textField.TextFieldRoundImage tfIngreso;
    private org.edisoncor.gui.textField.TextFieldRoundImage tfIngreso1;
    private org.edisoncor.gui.textField.TextFieldRoundImage tfJefe;
    private org.edisoncor.gui.textField.TextFieldRoundImage tfMarcaV;
    private org.edisoncor.gui.textField.TextFieldRoundImage tfModelo;
    private org.edisoncor.gui.textField.TextFieldRoundImage tfNombre;
    private org.edisoncor.gui.textField.TextFieldRoundImage tfNumeroExp;
    private org.edisoncor.gui.textField.TextFieldRoundImage tfPlacaV;
    private org.edisoncor.gui.textField.TextFieldRoundImage tfPuesto;
    private org.edisoncor.gui.textField.TextFieldRoundImage tfTelefono;
    private org.edisoncor.gui.textField.TextFieldRoundImage tfTipoH;
    private org.edisoncor.gui.textField.TextFieldRoundImage tfTipoV;
    private org.edisoncor.gui.textField.TextFieldRoundImage tfTrabajo;
    private org.edisoncor.gui.textField.TextFieldRoundImage tfValoracionV;
    private org.edisoncor.gui.textField.TextFieldRoundImage tfdescripcion;
    // End of variables declaration//GEN-END:variables

    private void addGarante() {
        String combo = (String) cbTipoGarante.getSelectedItem();
        changePanel();

        switch (combo) {
            case "Persona":
                if (!filterPersona()) {
                    return;
                }
                Persona persona = new Persona();
                persona.setIndentificacion(tfCedula.getText());
                persona.setNombre(tfNombre.getText());
                persona.setApellido(tfApellido.getText());
                persona.setCelular(tfCedula.getText());
                persona.setTelefono(tfTelefono.getText());
                persona.setCelular(tfCelular.getText());
                persona.setPuesto(tfPuesto.getText());
                persona.setIngreso(tfIngreso.getText());
                persona.setJefe(tfJefe.getText());
                persona.setTrabajo(tfTrabajo.getText());
                persona.setTipoGarante("PERSONA");
                lPersona.add(persona);
                tmCliene.setlCliente(lPersona);
                tCliente.setModel(tmCliene);
                clearPersona();

                break;
            case "Vehiculo":
                if (!filterVehiculo()) {
                    return;
                }
                Vehiculo vehiculo = new Vehiculo();
                vehiculo.setChasis(tfChasisV.getText());
                vehiculo.setModelo(tfModelo.getText());
                vehiculo.setTipo(tfTipoV.getText());
                vehiculo.setPlaca(tfPlacaV.getText());
                vehiculo.setMarca(tfMarcaV.getText());
                vehiculo.setValoracion(Integer.parseInt(tfValoracionV.getText()));
                vehiculo.setDescripcion(tfDescripcion.getText());
                vehiculo.setTipoGarante("VEHICULO");
                lVehiculo.add(vehiculo);
                tmVehiculo.setlVehiculo(lVehiculo);
                tVehiculo.setModel(tmVehiculo);

                clearVehiculo();

                break;

            case "Hipoteca":
                if (!filterHipoteca()) {
                    return;
                }
                Hipoteca hipoteca = new Hipoteca();
                hipoteca.setNumeroExp(tfNumeroExp.getText());
                hipoteca.setCodigo(tfCodigo.getText());
                hipoteca.setTipo(tfTipoH.getText());
                hipoteca.setValoracion(Integer.parseInt(tfIngreso1.getText()));
                hipoteca.setDescripcion(tfdescripcion.getText());
                hipoteca.setTipoGarante("HIPOTECA");
                lHipoteca.add(hipoteca);
                tmHipoteca.setlHipoteca(lHipoteca);
                tHipoteca.setModel(tmHipoteca);
                cleaHipoteca();

                break;
        }
    }

    public void init() {
        pnTableGarante.add(pnTablePersona);
        tmVehiculo.setlVehiculo(lVehiculo);
        tmCliene.setlCliente(lPersona);
        tmHipoteca.setlHipoteca(lHipoteca);
        tHipoteca.setModel(tmHipoteca);
        tCliente.setModel(tmCliene);
        tVehiculo.setModel(tmVehiculo);

    }

    private void changePanel() {
        pnTipo.removeAll();
        pnTableGarante.removeAll();

        String combo = (String) cbTipoGarante.getSelectedItem();
        if ("Persona".equals(combo)) {
            //           spnGarante.setLeftComponent(pnPersona);

            pnTipo.add(pnPersona);
            pnTableGarante.add(pnTablePersona);

        }
        if ("Vehiculo".equals(combo)) {
            //           spnGarante.setLeftComponent(pnVehiculo2);
            pnTipo.add(pnVehiculo);
            pnTableGarante.add(pnTableVehiculo);
        }
        if ("Hipoteca".equals(combo)) {
            //        spnGarante.setLeftComponent(pnHipoteca);
            pnTipo.add(pnHipoteca);
            pnTableGarante.add(pnTableHipoteca);
        }
        pnTipo.revalidate();
        pnTipo.repaint();
        pnTableGarante.revalidate();
        pnTableGarante.repaint();
    }

    public List<Persona> getlPersona() {
        return lPersona;
    }

    public void setlPersona(List<Persona> lPersona) {
        this.lPersona = lPersona;
    }

    public List<Vehiculo> getlVehiculo() {
        return lVehiculo;
    }

    public void setlVehiculo(List<Vehiculo> lVehiculo) {
        this.lVehiculo = lVehiculo;
    }

    public List<Hipoteca> getlHipoteca() {
        return lHipoteca;
    }

    public void setlHipoteca(List<Hipoteca> lHipoteca) {
        this.lHipoteca = lHipoteca;
    }

    public void clear() {
        lPersona = new ArrayList<>();
        lHipoteca = new ArrayList<>();
        lVehiculo = new ArrayList<>();

        tmCliene.setlCliente(lPersona);
        tmHipoteca.setlHipoteca(lHipoteca);
        tmVehiculo.setlVehiculo(lVehiculo);
        clearPersona();
        cleaHipoteca();
        clearVehiculo();

    }

    public void clearPersona() {
        tfCedula.setText("");
        tfPuesto.setText("");
        tfNombre.setText("");
        tfIngreso.setText("");
        tfApellido.setText("");
        tfJefe.setText("");
        tfCelular.setText("");
        tfTelefono.setText("");
        tfTrabajo.setText("");

    }

    public void clearVehiculo() {

        tfChasisV.setText("");
        tfPlacaV.setText("");
        tfModelo.setText("");
        tfMarcaV.setText("");
        tfTipoV.setText("");
        tfValoracionV.setText("");
        tfDescripcion.setText("");

    }

    public void cleaHipoteca() {

        tfNumeroExp.setText("");
        tfTipoH.setText("");
        tfCodigo.setText("");
        tfIngreso1.setText("");
        tfdescripcion.setText("");

    }

    private boolean filterPersona() {
        if ("".equals(tfCedula.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Debes especificar la cedula");
            tfCedula.requestFocus();
            return false;
        }
        if ("".equals(tfPuesto.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Debes especificar el puesto");
            tfPuesto.requestFocus();
            return false;
        }
        if ("".equals(tfNombre.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Debes especificar el nombre");
            tfNombre.requestFocus();
            return false;
        }
        if ("".equals(tfIngreso.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Debes especificar el ingreso");
            tfIngreso.requestFocus();
            return false;
        }
        if ("".equals(tfApellido.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Debes especificar el apellido");
            tfApellido.requestFocus();
            return false;
        }
        if ("".equals(tfJefe.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Debes especificar el jefe");
            tfJefe.requestFocus();
            return false;
        }
        if ("".equals(tfCelular.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Debes especificar el celular");
            tfCelular.requestFocus();
            return false;
        }
        if ("".equals(tfTelefono.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Debes especificar el trabajo");
            tfTelefono.requestFocus();
            return false;
        }
        if ("".equals(tfTrabajo.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Debes especificar el telefono");
            tfTrabajo.requestFocus();
            return false;
        }

        return true;
    }

    private boolean filterVehiculo() {
        if ("".equals(tfChasisV.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Debes especificar el chasis");
            tfChasisV.requestFocus();
            return false;
        }
        if ("".equals(tfPlacaV.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Debes especificar la placa");
            tfPlacaV.requestFocus();
            return false;
        }
        if ("".equals(tfModelo.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Debes especificar el modelo");
            tfModelo.requestFocus();
            return false;
        }
        if ("".equals(tfMarcaV.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Debes especificar la marca");
            tfMarcaV.requestFocus();
            return false;
        }
        if ("".equals(tfTipoV.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Debes especificar el vehiculo");
            tfTipoV.requestFocus();
            return false;
        }
        if ("".equals(tfValoracionV.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Debes especificar la valoracion");
            tfValoracionV.requestFocus();
            return false;
        }
        if ("".equals(tfDescripcion.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Debes especificar la descripcion");
            tfDescripcion.requestFocus();
            return false;
        }
        return true;
    }

    private boolean filterHipoteca() {
        if ("".equals(tfNumeroExp.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Debes especificar Numero expediente");
            tfNumeroExp.requestFocus();
            return false;
        }
        if ("".equals(tfTipoH.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Debes especificar el tipo");
            tfTipoH.requestFocus();
            return false;
        }
        if ("".equals(tfCodigo.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Debes especificar el codigo");
            tfCodigo.requestFocus();
            return false;
        }
        if ("".equals(tfIngreso1.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Debes especificar la valoracion");
            tfIngreso1.requestFocus();
            return false;
        }
        if ("".equals(tfdescripcion.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Debes especificar el vehiculo");
            tfdescripcion.requestFocus();
            return false;
        }
        return true;
    }

}
